// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Connection struct {
	Kind      ConnectionKind   `json:"kind"`
	Status    ConnectionStatus `json:"status"`
	Account   string           `json:"account"`
	TokenHint string           `json:"tokenHint"`
	Note      string           `json:"note"`
}

type DesignScreen struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	HTML string `json:"html"`
}

type Device struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	Trusted    bool   `json:"trusted"`
	Current    bool   `json:"current"`
	LastSeenAt string `json:"lastSeenAt"`
}

type ExportBundle struct {
	JSON string `json:"json"`
}

type GitPushResult struct {
	Ok   bool   `json:"ok"`
	Note string `json:"note"`
}

type Health struct {
	Ok      bool   `json:"ok"`
	Store   string `json:"store"`
	Version string `json:"version"`
	Mail    string `json:"mail"`
	Gdpr    bool   `json:"gdpr"`
	Llm     string `json:"llm"`
}

type JobLog struct {
	At      string   `json:"at"`
	Message string   `json:"message"`
	Role    ChatRole `json:"role"`
}

type LlmAdmin struct {
	Gdpr        bool             `json:"gdpr"`
	ActiveSlot  string           `json:"activeSlot"`
	McpRoot     string           `json:"mcpRoot"`
	SlotA       *LlmSlotCard     `json:"slotA"`
	SlotB       *LlmSlotCard     `json:"slotB"`
	Completions []*LlmCompletion `json:"completions"`
}

type LlmCompletion struct {
	At               string `json:"at"`
	Purpose          string `json:"purpose"`
	VersionName      string `json:"versionName"`
	Channel          string `json:"channel"`
	InputRedactions  int    `json:"inputRedactions"`
	OutputRedactions int    `json:"outputRedactions"`
	PromptPreview    string `json:"promptPreview"`
	OutputPreview    string `json:"outputPreview"`
}

type LlmSlotCard struct {
	Slot            string        `json:"slot"`
	Wired           bool          `json:"wired"`
	Role            string        `json:"role"`
	ActiveVersionID *string       `json:"activeVersionId,omitempty"`
	Versions        []*LlmVersion `json:"versions"`
}

type LlmStatus struct {
	Slot        string `json:"slot"`
	VersionName string `json:"versionName"`
	Channel     string `json:"channel"`
	Gdpr        bool   `json:"gdpr"`
}

type LlmVersion struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Note string `json:"note"`
}

type LocalActivate struct {
	Status ActivateStatus `json:"status"`
	URL    *string        `json:"url,omitempty"`
	Port   *int           `json:"port,omitempty"`
	Pid    *int           `json:"pid,omitempty"`
	Note   string         `json:"note"`
}

type LoginResult struct {
	Next         LoginNext `json:"next"`
	Token        *string   `json:"token,omitempty"`
	ChallengeID  *string   `json:"challengeId,omitempty"`
	User         *User     `json:"user,omitempty"`
	EmailSent    bool      `json:"emailSent"`
	EmailChannel string    `json:"emailChannel"`
}

type MaestroFlow struct {
	ID     string        `json:"id"`
	Name   string        `json:"name"`
	Yaml   string        `json:"yaml"`
	Result MaestroResult `json:"result"`
	Note   string        `json:"note"`
}

type MaestroStudio struct {
	Ready        bool            `json:"ready"`
	DeviceStatus string          `json:"deviceStatus"`
	Screens      []*DesignScreen `json:"screens"`
	Flows        []*MaestroFlow  `json:"flows"`
}

type MailMessage struct {
	ID        string        `json:"id"`
	Subject   string        `json:"subject"`
	Body      string        `json:"body"`
	Purpose   VerifyPurpose `json:"purpose"`
	CreatedAt string        `json:"createdAt"`
}

type Mutation struct {
}

type Project struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Brief         string         `json:"brief"`
	Stack         ProjectStack   `json:"stack"`
	Status        ProjectStatus  `json:"status"`
	RootPath      string         `json:"rootPath"`
	BackendTarget BackendTarget  `json:"backendTarget"`
	CreatedAt     string         `json:"createdAt"`
	Logs          []*JobLog      `json:"logs"`
	Files         []*ProjectFile `json:"files"`
	Maestro       *MaestroStudio `json:"maestro"`
	Activate      *LocalActivate `json:"activate"`
}

type ProjectFile struct {
	Path string `json:"path"`
	Kind string `json:"kind"`
}

// Icerde platform GraphQL — not the generated customer app API.
type Query struct {
}

type Session struct {
	ID          string `json:"id"`
	Current     bool   `json:"current"`
	CreatedAt   string `json:"createdAt"`
	DeviceLabel string `json:"deviceLabel"`
}

type TotpSetup struct {
	Secret     string `json:"secret"`
	OtpauthURL string `json:"otpauthUrl"`
}

type User struct {
	ID            string        `json:"id"`
	Email         string        `json:"email"`
	WorkspaceKind WorkspaceKind `json:"workspaceKind"`
	TotpEnabled   bool          `json:"totpEnabled"`
}

type ActivateStatus string

const (
	ActivateStatusIdle     ActivateStatus = "IDLE"
	ActivateStatusStarting ActivateStatus = "STARTING"
	ActivateStatusRunning  ActivateStatus = "RUNNING"
	ActivateStatusStopping ActivateStatus = "STOPPING"
	ActivateStatusFailed   ActivateStatus = "FAILED"
)

var AllActivateStatus = []ActivateStatus{
	ActivateStatusIdle,
	ActivateStatusStarting,
	ActivateStatusRunning,
	ActivateStatusStopping,
	ActivateStatusFailed,
}

func (e ActivateStatus) IsValid() bool {
	switch e {
	case ActivateStatusIdle, ActivateStatusStarting, ActivateStatusRunning, ActivateStatusStopping, ActivateStatusFailed:
		return true
	}
	return false
}

func (e ActivateStatus) String() string {
	return string(e)
}

func (e *ActivateStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivateStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivateStatus", str)
	}
	return nil
}

func (e ActivateStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivateStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivateStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BackendTarget string

const (
	BackendTargetLocal      BackendTarget = "LOCAL"
	BackendTargetSupabase   BackendTarget = "SUPABASE"
	BackendTargetCloudflare BackendTarget = "CLOUDFLARE"
	BackendTargetRender     BackendTarget = "RENDER"
)

var AllBackendTarget = []BackendTarget{
	BackendTargetLocal,
	BackendTargetSupabase,
	BackendTargetCloudflare,
	BackendTargetRender,
}

func (e BackendTarget) IsValid() bool {
	switch e {
	case BackendTargetLocal, BackendTargetSupabase, BackendTargetCloudflare, BackendTargetRender:
		return true
	}
	return false
}

func (e BackendTarget) String() string {
	return string(e)
}

func (e *BackendTarget) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BackendTarget(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BackendTarget", str)
	}
	return nil
}

func (e BackendTarget) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BackendTarget) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BackendTarget) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ChatRole string

const (
	ChatRoleUser   ChatRole = "USER"
	ChatRoleAgent  ChatRole = "AGENT"
	ChatRoleSystem ChatRole = "SYSTEM"
)

var AllChatRole = []ChatRole{
	ChatRoleUser,
	ChatRoleAgent,
	ChatRoleSystem,
}

func (e ChatRole) IsValid() bool {
	switch e {
	case ChatRoleUser, ChatRoleAgent, ChatRoleSystem:
		return true
	}
	return false
}

func (e ChatRole) String() string {
	return string(e)
}

func (e *ChatRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChatRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChatRole", str)
	}
	return nil
}

func (e ChatRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChatRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChatRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionKind string

const (
	ConnectionKindSupabase   ConnectionKind = "SUPABASE"
	ConnectionKindCloudflare ConnectionKind = "CLOUDFLARE"
	ConnectionKindGithub     ConnectionKind = "GITHUB"
	ConnectionKindVercel     ConnectionKind = "VERCEL"
	ConnectionKindRender     ConnectionKind = "RENDER"
)

var AllConnectionKind = []ConnectionKind{
	ConnectionKindSupabase,
	ConnectionKindCloudflare,
	ConnectionKindGithub,
	ConnectionKindVercel,
	ConnectionKindRender,
}

func (e ConnectionKind) IsValid() bool {
	switch e {
	case ConnectionKindSupabase, ConnectionKindCloudflare, ConnectionKindGithub, ConnectionKindVercel, ConnectionKindRender:
		return true
	}
	return false
}

func (e ConnectionKind) String() string {
	return string(e)
}

func (e *ConnectionKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionKind", str)
	}
	return nil
}

func (e ConnectionKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionStatus string

const (
	ConnectionStatusDisconnected ConnectionStatus = "DISCONNECTED"
	ConnectionStatusConnected    ConnectionStatus = "CONNECTED"
	ConnectionStatusFailed       ConnectionStatus = "FAILED"
)

var AllConnectionStatus = []ConnectionStatus{
	ConnectionStatusDisconnected,
	ConnectionStatusConnected,
	ConnectionStatusFailed,
}

func (e ConnectionStatus) IsValid() bool {
	switch e {
	case ConnectionStatusDisconnected, ConnectionStatusConnected, ConnectionStatusFailed:
		return true
	}
	return false
}

func (e ConnectionStatus) String() string {
	return string(e)
}

func (e *ConnectionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionStatus", str)
	}
	return nil
}

func (e ConnectionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LoginNext string

const (
	LoginNextSession    LoginNext = "SESSION"
	LoginNextDeviceCode LoginNext = "DEVICE_CODE"
	LoginNextTotp       LoginNext = "TOTP"
)

var AllLoginNext = []LoginNext{
	LoginNextSession,
	LoginNextDeviceCode,
	LoginNextTotp,
}

func (e LoginNext) IsValid() bool {
	switch e {
	case LoginNextSession, LoginNextDeviceCode, LoginNextTotp:
		return true
	}
	return false
}

func (e LoginNext) String() string {
	return string(e)
}

func (e *LoginNext) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LoginNext(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LoginNext", str)
	}
	return nil
}

func (e LoginNext) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LoginNext) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LoginNext) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MaestroResult string

const (
	MaestroResultSkipped MaestroResult = "SKIPPED"
	MaestroResultPassed  MaestroResult = "PASSED"
	MaestroResultFailed  MaestroResult = "FAILED"
)

var AllMaestroResult = []MaestroResult{
	MaestroResultSkipped,
	MaestroResultPassed,
	MaestroResultFailed,
}

func (e MaestroResult) IsValid() bool {
	switch e {
	case MaestroResultSkipped, MaestroResultPassed, MaestroResultFailed:
		return true
	}
	return false
}

func (e MaestroResult) String() string {
	return string(e)
}

func (e *MaestroResult) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MaestroResult(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MaestroResult", str)
	}
	return nil
}

func (e MaestroResult) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MaestroResult) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MaestroResult) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectStack string

const (
	ProjectStackExpo    ProjectStack = "EXPO"
	ProjectStackFlutter ProjectStack = "FLUTTER"
	ProjectStackNative  ProjectStack = "NATIVE"
)

var AllProjectStack = []ProjectStack{
	ProjectStackExpo,
	ProjectStackFlutter,
	ProjectStackNative,
}

func (e ProjectStack) IsValid() bool {
	switch e {
	case ProjectStackExpo, ProjectStackFlutter, ProjectStackNative:
		return true
	}
	return false
}

func (e ProjectStack) String() string {
	return string(e)
}

func (e *ProjectStack) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectStack(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectStack", str)
	}
	return nil
}

func (e ProjectStack) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectStack) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectStack) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectStatus string

const (
	ProjectStatusQueued  ProjectStatus = "QUEUED"
	ProjectStatusWriting ProjectStatus = "WRITING"
	ProjectStatusTesting ProjectStatus = "TESTING"
	ProjectStatusReady   ProjectStatus = "READY"
	ProjectStatusFailed  ProjectStatus = "FAILED"
)

var AllProjectStatus = []ProjectStatus{
	ProjectStatusQueued,
	ProjectStatusWriting,
	ProjectStatusTesting,
	ProjectStatusReady,
	ProjectStatusFailed,
}

func (e ProjectStatus) IsValid() bool {
	switch e {
	case ProjectStatusQueued, ProjectStatusWriting, ProjectStatusTesting, ProjectStatusReady, ProjectStatusFailed:
		return true
	}
	return false
}

func (e ProjectStatus) String() string {
	return string(e)
}

func (e *ProjectStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectStatus", str)
	}
	return nil
}

func (e ProjectStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VerifyPurpose string

const (
	VerifyPurposeNewDevice       VerifyPurpose = "NEW_DEVICE"
	VerifyPurposeLoginChallenge  VerifyPurpose = "LOGIN_CHALLENGE"
	VerifyPurposeEmailVerify     VerifyPurpose = "EMAIL_VERIFY"
	VerifyPurposeSuspiciousLogin VerifyPurpose = "SUSPICIOUS_LOGIN"
)

var AllVerifyPurpose = []VerifyPurpose{
	VerifyPurposeNewDevice,
	VerifyPurposeLoginChallenge,
	VerifyPurposeEmailVerify,
	VerifyPurposeSuspiciousLogin,
}

func (e VerifyPurpose) IsValid() bool {
	switch e {
	case VerifyPurposeNewDevice, VerifyPurposeLoginChallenge, VerifyPurposeEmailVerify, VerifyPurposeSuspiciousLogin:
		return true
	}
	return false
}

func (e VerifyPurpose) String() string {
	return string(e)
}

func (e *VerifyPurpose) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VerifyPurpose(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VerifyPurpose", str)
	}
	return nil
}

func (e VerifyPurpose) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VerifyPurpose) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VerifyPurpose) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceKind string

const (
	WorkspaceKindPersonal     WorkspaceKind = "PERSONAL"
	WorkspaceKindOrganization WorkspaceKind = "ORGANIZATION"
)

var AllWorkspaceKind = []WorkspaceKind{
	WorkspaceKindPersonal,
	WorkspaceKindOrganization,
}

func (e WorkspaceKind) IsValid() bool {
	switch e {
	case WorkspaceKindPersonal, WorkspaceKindOrganization:
		return true
	}
	return false
}

func (e WorkspaceKind) String() string {
	return string(e)
}

func (e *WorkspaceKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceKind", str)
	}
	return nil
}

func (e WorkspaceKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
