package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/icerde/api/internal/store"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, deviceFingerprint string, deviceLabel string) (*LoginResult, error) {
	result, err := r.Auth.Register(ctx, email, password, deviceFingerprint, deviceLabel, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, deviceFingerprint string, deviceLabel string) (*LoginResult, error) {
	result, err := r.Auth.Login(ctx, email, password, deviceFingerprint, deviceLabel, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// VerifyCode is the resolver for the verifyCode field.
func (r *mutationResolver) VerifyCode(ctx context.Context, challengeID string, code string, trustDevice bool) (*LoginResult, error) {
	result, err := r.Auth.VerifyCode(ctx, challengeID, code, trustDevice, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// VerifyLink is the resolver for the verifyLink field.
func (r *mutationResolver) VerifyLink(ctx context.Context, token string, deviceFingerprint string, deviceLabel string) (*LoginResult, error) {
	result, err := r.Auth.VerifyLink(ctx, token, deviceFingerprint, deviceLabel, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// VerifyTotp is the resolver for the verifyTotp field.
func (r *mutationResolver) VerifyTotp(ctx context.Context, challengeID string, code string) (*LoginResult, error) {
	result, err := r.Auth.VerifyTotp(ctx, challengeID, code, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// EnableTotp is the resolver for the enableTotp field.
func (r *mutationResolver) EnableTotp(ctx context.Context) (*TotpSetup, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	secret, url, err := r.Auth.EnableTotp(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &TotpSetup{Secret: secret, OtpauthURL: url}, nil
}

// ConfirmTotp is the resolver for the confirmTotp field.
func (r *mutationResolver) ConfirmTotp(ctx context.Context, code string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	if err := r.Auth.ConfirmTotp(ctx, user.ID, code); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// DisableTotp is the resolver for the disableTotp field.
func (r *mutationResolver) DisableTotp(ctx context.Context, code string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	if err := r.Auth.DisableTotp(ctx, user.ID, code); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, id string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	sessions, err := r.Auth.Store.ListSessions(ctx, user.ID)
	if err != nil {
		return false, gqlErr(err)
	}
	found := false
	for _, session := range sessions {
		if session.ID == id {
			found = true
			break
		}
	}
	if !found {
		return false, gqlErr(store.ErrNotFound)
	}
	if err := r.Auth.Store.RevokeSession(ctx, id); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// RevokeDevice is the resolver for the revokeDevice field.
func (r *mutationResolver) RevokeDevice(ctx context.Context, id string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	devices, err := r.Auth.Store.ListDevices(ctx, user.ID)
	if err != nil {
		return false, gqlErr(err)
	}
	found := false
	for _, device := range devices {
		if device.ID == id {
			found = true
			break
		}
	}
	if !found {
		return false, gqlErr(store.ErrNotFound)
	}
	if err := r.Auth.Store.RevokeDevice(ctx, id); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	if err := r.Auth.Logout(ctx, TokenFrom(ctx)); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string, brief string, stack ProjectStack) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	row, err := r.Factory.Create(ctx, user.ID, name, brief, string(stack))
	if err != nil {
		return nil, gqlErr(err)
	}
	return r.projectPayload(ctx, user.ID, row.ID, true)
}

// SendProjectMessage is the resolver for the sendProjectMessage field.
func (r *mutationResolver) SendProjectMessage(ctx context.Context, projectID string, body string) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	row, err := r.Factory.SendMessage(ctx, user.ID, projectID, body)
	if err != nil {
		return nil, gqlErr(err)
	}
	return r.projectPayload(ctx, user.ID, row.ID, true)
}

// SetActiveVersion is the resolver for the setActiveVersion field.
func (r *mutationResolver) SetActiveVersion(ctx context.Context, id string) (*LlmAdmin, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if err := r.LLM.SetActiveA(ctx, id); err != nil {
		return nil, gqlErr(err)
	}
	return r.llmAdminPayload(ctx, user.ID)
}

// SetMcpRoot is the resolver for the setMcpRoot field.
func (r *mutationResolver) SetMcpRoot(ctx context.Context, path string) (*LlmAdmin, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if err := r.LLM.SetMcpRoot(ctx, path); err != nil {
		return nil, gqlErr(err)
	}
	return r.llmAdminPayload(ctx, user.ID)
}

// DeleteMe is the resolver for the deleteMe field.
func (r *mutationResolver) DeleteMe(ctx context.Context, wipeProjects bool) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	_ = r.Auth.Logout(ctx, TokenFrom(ctx))
	if err := r.Auth.Store.DeleteUserData(ctx, user.ID, wipeProjects); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*Health, error) {
	ok := r.Auth.Store.Ping(ctx) == nil
	mail := "inbox"
	if r.Auth.Mailer != nil {
		mail = r.Auth.Mailer.Channel()
	}
	llmName := "off"
	if r.LLM != nil {
		if version, channel, err := r.LLM.Status(ctx); err == nil {
			llmName = version.Name + "/" + channel
		}
	}
	return &Health{Ok: ok, Store: r.Auth.Store.Name(), Version: apiVersion, Mail: mail, Gdpr: r.LLM != nil, Llm: llmName}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		if errors.Is(err, store.ErrUnauthorized) {
			return nil, nil
		}
		return nil, gqlErr(err)
	}
	return mapUser(*user)
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Factory.List(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapProjects(rows)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := r.projectPayload(ctx, user.ID, id, true)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// MaestroStudio is the resolver for the maestroStudio field.
func (r *queryResolver) MaestroStudio(ctx context.Context, projectID string) (*MaestroStudio, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	studio, err := r.Factory.Maestro(ctx, user.ID, projectID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := mapMaestro(studio)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context) ([]*Device, error) {
	user, sess, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Auth.Store.ListDevices(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*Device, 0, len(rows))
	for _, row := range rows {
		item := row
		out = append(out, &Device{
			ID:         item.ID,
			Label:      item.Label,
			Trusted:    item.Trusted,
			Current:    item.ID == sess.DeviceID,
			LastSeenAt: item.LastSeen.UTC().Format(time.RFC3339),
		})
	}
	return out, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context) ([]*Session, error) {
	user, current, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Auth.Store.ListSessions(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*Session, 0, len(rows))
	for _, row := range rows {
		item := row
		out = append(out, &Session{
			ID:          item.ID,
			Current:     item.ID == current.ID,
			CreatedAt:   item.CreatedAt.UTC().Format(time.RFC3339),
			DeviceLabel: item.DeviceLabel,
		})
	}
	return out, nil
}

// Mailbox is the resolver for the mailbox field.
func (r *queryResolver) Mailbox(ctx context.Context) ([]*MailMessage, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Auth.Store.ListMail(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*MailMessage, 0, len(rows))
	for _, row := range rows {
		msg, err := mapMail(row)
		if err != nil {
			return nil, gqlErr(err)
		}
		out = append(out, msg)
	}
	return out, nil
}

// ChallengeMailbox is the resolver for the challengeMailbox field.
func (r *queryResolver) ChallengeMailbox(ctx context.Context, challengeID string) (*MailMessage, error) {
	mail, err := r.Auth.Store.MailByChallenge(ctx, challengeID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, gqlErr(err)
	}
	return mapMail(*mail)
}

// LlmAdmin is the resolver for the llmAdmin field.
func (r *queryResolver) LlmAdmin(ctx context.Context) (*LlmAdmin, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := r.llmAdminPayload(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// LlmStatus is the resolver for the llmStatus field.
func (r *queryResolver) LlmStatus(ctx context.Context) (*LlmStatus, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return nil, gqlErr(err)
	}
	version, channel, err := r.LLM.Status(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &LlmStatus{Slot: "A", VersionName: version.Name, Channel: channel, Gdpr: true}, nil
}

// McpReadFile is the resolver for the mcpReadFile field.
func (r *queryResolver) McpReadFile(ctx context.Context, relativePath string) (string, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return "", gqlErr(err)
	}
	body, err := r.LLM.ReadProjectFile(ctx, relativePath)
	if err != nil {
		return "", gqlErr(err)
	}
	return body, nil
}

// ExportMe is the resolver for the exportMe field.
func (r *queryResolver) ExportMe(ctx context.Context) (*ExportBundle, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	projects, err := r.Factory.List(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	audits, err := r.LLM.Store.ListAudit(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	names := make([]string, 0, len(projects))
	for _, project := range projects {
		names = append(names, project.Name)
	}
	payload, err := json.Marshal(map[string]any{
		"email":    user.Email,
		"projects": names,
		"audits":   len(audits),
	})
	if err != nil {
		return nil, gqlErr(err)
	}
	return &ExportBundle{JSON: string(payload)}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
