package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/cherry/api/internal/llm"
	"github.com/cherry/api/internal/store"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, deviceFingerprint string, deviceLabel string) (*LoginResult, error) {
	result, err := r.Auth.Register(ctx, email, password, deviceFingerprint, deviceLabel, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, deviceFingerprint string, deviceLabel string) (*LoginResult, error) {
	result, err := r.Auth.Login(ctx, email, password, deviceFingerprint, deviceLabel, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// VerifyCode is the resolver for the verifyCode field.
func (r *mutationResolver) VerifyCode(ctx context.Context, challengeID string, code string, trustDevice bool) (*LoginResult, error) {
	result, err := r.Auth.VerifyCode(ctx, challengeID, code, trustDevice, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// VerifyLink is the resolver for the verifyLink field.
func (r *mutationResolver) VerifyLink(ctx context.Context, token string, deviceFingerprint string, deviceLabel string) (*LoginResult, error) {
	result, err := r.Auth.VerifyLink(ctx, token, deviceFingerprint, deviceLabel, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// VerifyTotp is the resolver for the verifyTotp field.
func (r *mutationResolver) VerifyTotp(ctx context.Context, challengeID string, code string) (*LoginResult, error) {
	result, err := r.Auth.VerifyTotp(ctx, challengeID, code, IPFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapLoginResult(result)
}

// EnableTotp is the resolver for the enableTotp field.
func (r *mutationResolver) EnableTotp(ctx context.Context) (*TotpSetup, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	secret, url, err := r.Auth.EnableTotp(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &TotpSetup{Secret: secret, OtpauthURL: url}, nil
}

// ConfirmTotp is the resolver for the confirmTotp field.
func (r *mutationResolver) ConfirmTotp(ctx context.Context, code string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	if err := r.Auth.ConfirmTotp(ctx, user.ID, code); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// DisableTotp is the resolver for the disableTotp field.
func (r *mutationResolver) DisableTotp(ctx context.Context, code string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	if err := r.Auth.DisableTotp(ctx, user.ID, code); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, id string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	sessions, err := r.Auth.Store.ListSessions(ctx, user.ID)
	if err != nil {
		return false, gqlErr(err)
	}
	found := false
	for _, session := range sessions {
		if session.ID == id {
			found = true
			break
		}
	}
	if !found {
		return false, gqlErr(store.ErrNotFound)
	}
	if err := r.Auth.Store.RevokeSession(ctx, id); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// RevokeDevice is the resolver for the revokeDevice field.
func (r *mutationResolver) RevokeDevice(ctx context.Context, id string) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	devices, err := r.Auth.Store.ListDevices(ctx, user.ID)
	if err != nil {
		return false, gqlErr(err)
	}
	found := false
	for _, device := range devices {
		if device.ID == id {
			found = true
			break
		}
	}
	if !found {
		return false, gqlErr(store.ErrNotFound)
	}
	if err := r.Auth.Store.RevokeDevice(ctx, id); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	if err := r.Auth.Logout(ctx, TokenFrom(ctx)); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string, brief string, stack ProjectStack, backendTarget *BackendTarget) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	backend := ""
	if backendTarget != nil {
		backend = string(*backendTarget)
	}
	row, err := r.Factory.Create(ctx, user.ID, name, brief, string(stack), backend)
	if err != nil {
		return nil, gqlErr(err)
	}
	return r.projectPayload(ctx, user.ID, row.ID, true)
}

// SendProjectMessage is the resolver for the sendProjectMessage field.
func (r *mutationResolver) SendProjectMessage(ctx context.Context, projectID string, body string) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	row, err := r.Factory.SendMessage(ctx, user.ID, projectID, body)
	if err != nil {
		return nil, gqlErr(err)
	}
	return r.projectPayload(ctx, user.ID, row.ID, true)
}

// ActivateProject is the resolver for the activateProject field.
func (r *mutationResolver) ActivateProject(ctx context.Context, id string) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if _, err := r.Factory.Activate(ctx, user.ID, id); err != nil {
		return nil, gqlErr(err)
	}
	return r.projectPayload(ctx, user.ID, id, true)
}

// DeactivateProject is the resolver for the deactivateProject field.
func (r *mutationResolver) DeactivateProject(ctx context.Context, id string) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if _, err := r.Factory.Deactivate(ctx, user.ID, id); err != nil {
		return nil, gqlErr(err)
	}
	return r.projectPayload(ctx, user.ID, id, true)
}

// RunMaestro is the resolver for the runMaestro field.
func (r *mutationResolver) RunMaestro(ctx context.Context, projectID string) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if _, err := r.Factory.RunMaestro(ctx, user.ID, projectID); err != nil {
		return nil, gqlErr(err)
	}
	return r.projectPayload(ctx, user.ID, projectID, true)
}

// ConnectProvider is the resolver for the connectProvider field.
func (r *mutationResolver) ConnectProvider(ctx context.Context, kind ConnectionKind, account string, token string) (*Connection, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Connect == nil {
		return nil, gqlErr(store.ErrNotFound)
	}
	row, err := r.Connect.Connect(ctx, user.ID, string(kind), account, token)
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := r.connectionPayload(row)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// StartConnectionOAuth is the resolver for the startConnectionOAuth field.
func (r *mutationResolver) StartConnectionOAuth(ctx context.Context, kind ConnectionKind) (*OAuthStart, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Connect == nil {
		return nil, gqlErr(store.ErrNotFound)
	}
	start, err := r.Connect.StartOAuth(ctx, user.ID, user.Email, string(kind))
	if err != nil {
		return nil, gqlErr(err)
	}
	mode, err := mapOAuthMode(start.Mode)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &OAuthStart{
		AuthorizeURL: start.AuthorizeURL,
		State:        start.State,
		Mode:         mode,
	}, nil
}

// CompleteConnectionOAuth is the resolver for the completeConnectionOAuth field.
func (r *mutationResolver) CompleteConnectionOAuth(ctx context.Context, code string, state string) (*Connection, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Connect == nil {
		return nil, gqlErr(store.ErrNotFound)
	}
	row, err := r.Connect.CompleteOAuth(ctx, user.ID, code, state)
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := r.connectionPayload(row)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// DisconnectProvider is the resolver for the disconnectProvider field.
func (r *mutationResolver) DisconnectProvider(ctx context.Context, kind ConnectionKind) (*Connection, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Connect == nil {
		return nil, gqlErr(store.ErrNotFound)
	}
	row, err := r.Connect.Disconnect(ctx, user.ID, string(kind))
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := r.connectionPayload(row)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// PushProjectGithub is the resolver for the pushProjectGithub field.
func (r *mutationResolver) PushProjectGithub(ctx context.Context, projectID string, repo string) (*GitPushResult, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Connect == nil {
		return nil, gqlErr(store.ErrNotFound)
	}
	project, err := r.Factory.Get(ctx, user.ID, projectID)
	if err != nil {
		return nil, gqlErr(err)
	}
	res, err := r.Connect.PushGitHub(ctx, user.ID, project.RootPath, repo)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &GitPushResult{Ok: res.OK, Note: res.Note}, nil
}

// SetActiveVersion is the resolver for the setActiveVersion field.
func (r *mutationResolver) SetActiveVersion(ctx context.Context, id string) (*LlmAdmin, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if err := r.LLM.SetActive(ctx, id); err != nil {
		return nil, gqlErr(err)
	}
	return r.llmAdminPayload(ctx, user.ID)
}

// SetMcpRoot is the resolver for the setMcpRoot field.
func (r *mutationResolver) SetMcpRoot(ctx context.Context, path string) (*LlmAdmin, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if err := r.LLM.SetMcpRoot(ctx, path); err != nil {
		return nil, gqlErr(err)
	}
	return r.llmAdminPayload(ctx, user.ID)
}

// RegisterLlmVersion is the resolver for the registerLlmVersion field.
func (r *mutationResolver) RegisterLlmVersion(ctx context.Context, slot string, name string, note string, checkpointRef string) (*LlmAdmin, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if _, err := r.LLM.RegisterVersion(ctx, slot, name, note, checkpointRef); err != nil {
		return nil, gqlErr(err)
	}
	return r.llmAdminPayload(ctx, user.ID)
}

// StartColabBridge is the resolver for the startColabBridge field.
func (r *mutationResolver) StartColabBridge(ctx context.Context) (*ColabBridge, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Bridge == nil {
		return r.colabBridgePayload(), nil
	}
	r.Bridge.Start(user.ID)
	return r.colabBridgePayload(), nil
}

// StopColabBridge is the resolver for the stopColabBridge field.
func (r *mutationResolver) StopColabBridge(ctx context.Context) (*ColabBridge, error) {
	_, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Bridge != nil {
		r.Bridge.Stop()
	}
	return r.colabBridgePayload(), nil
}

// SetColabInferenceURL is the resolver for the setColabInferenceUrl field.
func (r *mutationResolver) SetColabInferenceURL(ctx context.Context, slot string, url string) (*ColabInference, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return nil, gqlErr(err)
	}
	parsed, err := llm.ParseSlot(slot)
	if err != nil {
		return nil, gqlErr(err)
	}
	r.LLM.SetColabInferenceURL(parsed, url)
	return r.colabInferencePayload(parsed), nil
}

// DeleteMe is the resolver for the deleteMe field.
func (r *mutationResolver) DeleteMe(ctx context.Context, wipeProjects bool) (bool, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return false, gqlErr(err)
	}
	_ = r.Auth.Logout(ctx, TokenFrom(ctx))
	if err := r.Auth.Store.DeleteUserData(ctx, user.ID, wipeProjects); err != nil {
		return false, gqlErr(err)
	}
	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*Health, error) {
	ok := r.Auth.Store.Ping(ctx) == nil
	mail := "inbox"
	if r.Auth.Mailer != nil {
		mail = r.Auth.Mailer.Channel()
	}
	llmName := "off"
	if r.LLM != nil {
		if version, channel, err := r.LLM.Status(ctx); err == nil {
			llmName = version.Name + "/" + channel
		}
	}
	return &Health{Ok: ok, Store: r.Auth.Store.Name(), Version: apiVersion, Mail: mail, Gdpr: r.LLM != nil, Llm: llmName}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		if errors.Is(err, store.ErrUnauthorized) {
			return nil, nil
		}
		return nil, gqlErr(err)
	}
	return mapUser(*user)
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Factory.List(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapProjects(rows)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*Project, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := r.projectPayload(ctx, user.ID, id, true)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// MaestroStudio is the resolver for the maestroStudio field.
func (r *queryResolver) MaestroStudio(ctx context.Context, projectID string) (*MaestroStudio, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	studio, err := r.Factory.Maestro(ctx, user.ID, projectID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := mapMaestro(studio)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context) ([]*Device, error) {
	user, sess, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Auth.Store.ListDevices(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*Device, 0, len(rows))
	for _, row := range rows {
		item := row
		out = append(out, &Device{
			ID:         item.ID,
			Label:      item.Label,
			Trusted:    item.Trusted,
			Current:    item.ID == sess.DeviceID,
			LastSeenAt: item.LastSeen.UTC().Format(time.RFC3339),
		})
	}
	return out, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context) ([]*Session, error) {
	user, current, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Auth.Store.ListSessions(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*Session, 0, len(rows))
	for _, row := range rows {
		item := row
		out = append(out, &Session{
			ID:          item.ID,
			Current:     item.ID == current.ID,
			CreatedAt:   item.CreatedAt.UTC().Format(time.RFC3339),
			DeviceLabel: item.DeviceLabel,
		})
	}
	return out, nil
}

// Mailbox is the resolver for the mailbox field.
func (r *queryResolver) Mailbox(ctx context.Context) ([]*MailMessage, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	rows, err := r.Auth.Store.ListMail(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*MailMessage, 0, len(rows))
	for _, row := range rows {
		msg, err := mapMail(row)
		if err != nil {
			return nil, gqlErr(err)
		}
		out = append(out, msg)
	}
	return out, nil
}

// ChallengeMailbox is the resolver for the challengeMailbox field.
func (r *queryResolver) ChallengeMailbox(ctx context.Context, challengeID string) (*MailMessage, error) {
	mail, err := r.Auth.Store.MailByChallenge(ctx, challengeID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, gqlErr(err)
	}
	return mapMail(*mail)
}

// LlmAdmin is the resolver for the llmAdmin field.
func (r *queryResolver) LlmAdmin(ctx context.Context) (*LlmAdmin, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := r.llmAdminPayload(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// LlmStatus is the resolver for the llmStatus field.
func (r *queryResolver) LlmStatus(ctx context.Context) (*LlmStatus, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return nil, gqlErr(err)
	}
	snap, err := r.LLM.Snapshot(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	slot := string(snap.LastSlot)
	if slot == "" {
		slot = "A"
	}
	versionName := snap.VersionA
	if snap.LastSlot == "B" {
		versionName = snap.VersionB
	}
	return &LlmStatus{
		Slot:        slot,
		VersionName: versionName,
		Channel:     snap.Channel,
		Gdpr:        true,
		Queued:      snap.Queued,
		OccupancyA:  occupancyFromBusy(snap.BusyA),
		OccupancyB:  occupancyFromBusy(snap.BusyB),
		VersionA:    snap.VersionA,
		VersionB:    snap.VersionB,
	}, nil
}

// McpReadFile is the resolver for the mcpReadFile field.
func (r *queryResolver) McpReadFile(ctx context.Context, relativePath string) (string, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return "", gqlErr(err)
	}
	body, err := r.LLM.ReadProjectFile(ctx, relativePath)
	if err != nil {
		return "", gqlErr(err)
	}
	return body, nil
}

// ExportMe is the resolver for the exportMe field.
func (r *queryResolver) ExportMe(ctx context.Context) (*ExportBundle, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	projects, err := r.Factory.List(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	audits, err := r.LLM.Store.ListAudit(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	names := make([]string, 0, len(projects))
	for _, project := range projects {
		names = append(names, project.Name)
	}
	payload, err := json.Marshal(map[string]any{
		"email":    user.Email,
		"projects": names,
		"audits":   len(audits),
	})
	if err != nil {
		return nil, gqlErr(err)
	}
	return &ExportBundle{JSON: string(payload)}, nil
}

// TrainingPack is the resolver for the trainingPack field.
func (r *queryResolver) TrainingPack(ctx context.Context) (*TrainingPack, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	pack, err := r.buildTrainingPack(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out, err := trainingPackPayload(pack)
	if err != nil {
		return nil, gqlErr(err)
	}
	return out, nil
}

// Connections is the resolver for the connections field.
func (r *queryResolver) Connections(ctx context.Context) ([]*Connection, error) {
	user, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx))
	if err != nil {
		return nil, gqlErr(err)
	}
	if r.Connect == nil {
		return nil, gqlErr(store.ErrNotFound)
	}
	rows, err := r.Connect.Catalog(ctx, user.ID)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*Connection, 0, len(rows))
	for _, row := range rows {
		item, err := r.connectionPayload(row)
		if err != nil {
			return nil, gqlErr(err)
		}
		out = append(out, item)
	}
	return out, nil
}

// ColabBridge is the resolver for the colabBridge field.
func (r *queryResolver) ColabBridge(ctx context.Context) (*ColabBridge, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return nil, gqlErr(err)
	}
	return r.colabBridgePayload(), nil
}

// ColabInferenceA is the resolver for the colabInferenceA field.
func (r *queryResolver) ColabInferenceA(ctx context.Context) (*ColabInference, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return nil, gqlErr(err)
	}
	return r.colabInferencePayload(store.SlotA), nil
}

// ColabInferenceB is the resolver for the colabInferenceB field.
func (r *queryResolver) ColabInferenceB(ctx context.Context) (*ColabInference, error) {
	if _, _, err := r.Auth.SessionUser(ctx, TokenFrom(ctx)); err != nil {
		return nil, gqlErr(err)
	}
	return r.colabInferencePayload(store.SlotB), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
