package llm

// SeedExamples is the baseline SFT corpus when live studio traces are thin.
// Keep outputs concrete (real files / Maestro YAML), not one-line stubs.
func SeedExamples() []PackExample {
	return []PackExample{
		// —— briefs ——
		{
			ID:          "seed-expo-brief-coffee",
			Kind:        "brief",
			Source:      "seed",
			Instruction: "Cherry stüdyosu için mobil uygulama planı yaz. Seçilen yığın ve Clean Architecture. preview/ HTML site yazma. PII uydurma.",
			Input:       "Proje: Kahve sipariş\nYığın: EXPO\nBrif:\nMahalle kahvecisi için sipariş listesi. Giriş ve ana ekran. Yerel backend.",
			Output:      "Plan (Expo SDK 57, TypeScript):\n- frontend/: domain / data / presentation.\n- backend/: yerel HTTP (127.0.0.1), barındırma yok.\n- maestro/: login.yaml + home.yaml.\n- preview/ yalnızca stüdyo maketi; zip’e girmez.\nTeslim: klasör / zip / git — müşteri kendi hesabına bağlar.",
			Meta:        map[string]string{"stack": "EXPO", "kind": "brief"},
		},
		{
			ID:          "seed-flutter-brief-fitness",
			Kind:        "brief",
			Source:      "seed",
			Instruction: "Cherry stüdyosu için mobil uygulama planı yaz. Seçilen yığın ve Clean Architecture. preview/ HTML site yazma. PII uydurma.",
			Input:       "Proje: Antrenman günlüğü\nYığın: FLUTTER\nBrif:\nGünlük egzersiz kaydı. Liste + detay. Offline-first yerel API.",
			Output:      "Plan (Flutter 3.x, Dart):\n- frontend/lib/features/{auth,home}/ domain / data / presentation.\n- backend/: Go veya Dart yerel sunucu, hosting yok.\n- maestro/: login.yaml + workout_list.yaml.\n- Clean Architecture katmanlarını karıştırma; preview/ zip dışı.",
			Meta:        map[string]string{"stack": "FLUTTER", "kind": "brief"},
		},
		{
			ID:          "seed-native-brief-notes",
			Kind:        "brief",
			Source:      "seed",
			Instruction: "Cherry stüdyosu için mobil uygulama planı yaz. Seçilen yığın ve Clean Architecture. preview/ HTML site yazma. PII uydurma.",
			Input:       "Proje: Not defteri\nYığın: NATIVE\nBrif:\nSwiftUI not listesi ve düzenleme. Yerel backend.",
			Output:      "Plan (SwiftUI):\n- frontend/Domain, frontend/Data, frontend/Presentation.\n- backend/: yerel HTTP.\n- maestro/: login.yaml + notes.yaml.\n- UIKit storyboard / HTML site üretme.",
			Meta:        map[string]string{"stack": "NATIVE", "kind": "brief"},
		},
		{
			ID:          "seed-expo-brief-inventory",
			Kind:        "brief",
			Source:      "seed",
			Instruction: "Cherry stüdyosu için mobil uygulama planı yaz. Seçilen yığın ve Clean Architecture. preview/ HTML site yazma. PII uydurma.",
			Input:       "Proje: Depo stok\nYığın: EXPO\nBrif:\nÜrün stok listesi, ekle/sil. Auth zorunlu. Supabase sonra Bağlantılar’dan; şimdi local.",
			Output:      "Plan (Expo):\n1) İskele: frontend domain-data-presentation + backend local.\n2) Auth ekranı + stok listesi.\n3) maestro login + inventory.\n4) Backend target sonra Bağlantılar’dan değişir; Cherry host etmez.\npreview/ teslim değil.",
			Meta:        map[string]string{"stack": "EXPO", "kind": "brief"},
		},
		{
			ID:          "seed-workers-capacity",
			Kind:        "brief",
			Source:      "seed",
			Instruction: "Cherry stüdyosu için mobil uygulama planı yaz. Seçilen yığın ve Clean Architecture. preview/ HTML site yazma. PII uydurma.",
			Input:       "Proje: Kapasite notu\nYığın: EXPO\nBrif:\nA ve B aynı işi yapar. Boş işçi alır; ikisi meşgulse kuyruk. Kod/test ayrımı yok.",
			Output:      "Plan:\n- Tek tarif, iki kapasite işçisi (A/B).\n- Versiyon pointer’ı yalnızca sonraki cevapları değiştirir.\n- Colab üretim inferansı değil; checkpoint stüdyoya döner.\n- OpenCode yazar; LLM plan/yama üretir.",
			Meta:        map[string]string{"stack": "EXPO", "kind": "capacity"},
		},

		// —— Expo source ——
		{
			ID:          "seed-expo-entity-item",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: frontend/src/domain/entities/item.ts\nBrif: Kahve sipariş listesi.",
			Output:      "export type Item = {\n  id: string;\n  title: string;\n  quantity: number;\n};\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/src/domain/entities/item.ts"},
		},
		{
			ID:          "seed-expo-entity-user",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: frontend/src/domain/entities/user.ts\nBrif: E-posta ile giriş; telefon kimlik değil.",
			Output:      "export type User = {\n  id: string;\n  email: string;\n};\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/src/domain/entities/user.ts"},
		},
		{
			ID:          "seed-expo-repo",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: frontend/src/data/repositories/itemRepository.ts\nBrif: Yerel HTTP’den sipariş listesi.",
			Output:      "import type { Item } from '../../domain/entities/item';\n\nconst BASE = 'http://127.0.0.1:47001';\n\nexport async function listItems(): Promise<Item[]> {\n  const res = await fetch(`${BASE}/items`);\n  if (!res.ok) throw new Error('items_failed');\n  return (await res.json()) as Item[];\n}\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/src/data/repositories/itemRepository.ts"},
		},
		{
			ID:          "seed-expo-usecase",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: frontend/src/domain/usecases/listItems.ts\nBrif: Domain use case; UI bilmesin.",
			Output:      "import type { Item } from '../entities/item';\nimport { listItems as fetchItems } from '../../data/repositories/itemRepository';\n\nexport async function listItems(): Promise<Item[]> {\n  return fetchItems();\n}\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/src/domain/usecases/listItems.ts"},
		},
		{
			ID:          "seed-expo-screen-home",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: frontend/src/presentation/screens/HomeScreen.tsx\nBrif: Sipariş listesi; boş ve hata durumu.",
			Output:      "import { useEffect, useState } from 'react';\nimport { ActivityIndicator, FlatList, Text, View } from 'react-native';\nimport type { Item } from '../../domain/entities/item';\nimport { listItems } from '../../domain/usecases/listItems';\n\nexport function HomeScreen() {\n  const [items, setItems] = useState<Item[] | null>(null);\n  const [error, setError] = useState<string | null>(null);\n\n  useEffect(() => {\n    listItems()\n      .then(setItems)\n      .catch(() => setError('Liste yüklenemedi'));\n  }, []);\n\n  if (error) return <Text>{error}</Text>;\n  if (!items) return <ActivityIndicator />;\n  if (items.length === 0) return <Text>Sipariş yok</Text>;\n\n  return (\n    <View>\n      <Text>Siparişler</Text>\n      <FlatList\n        data={items}\n        keyExtractor={(item) => item.id}\n        renderItem={({ item }) => <Text>{item.title}</Text>}\n      />\n    </View>\n  );\n}\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/src/presentation/screens/HomeScreen.tsx"},
		},
		{
			ID:          "seed-expo-screen-login",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: frontend/src/presentation/screens/LoginScreen.tsx\nBrif: E-posta + şifre; SMS yok.",
			Output:      "import { useState } from 'react';\nimport { Button, Text, TextInput, View } from 'react-native';\n\nexport function LoginScreen({ onSubmit }: { onSubmit: (email: string, password: string) => void }) {\n  const [email, setEmail] = useState('');\n  const [password, setPassword] = useState('');\n  const [error, setError] = useState<string | null>(null);\n\n  return (\n    <View>\n      <Text>Giriş</Text>\n      <TextInput\n        autoCapitalize=\"none\"\n        keyboardType=\"email-address\"\n        placeholder=\"E-posta\"\n        value={email}\n        onChangeText={setEmail}\n      />\n      <TextInput\n        secureTextEntry\n        placeholder=\"Şifre\"\n        value={password}\n        onChangeText={setPassword}\n      />\n      {error ? <Text>{error}</Text> : null}\n      <Button\n        title=\"Giriş yap\"\n        onPress={() => {\n          if (!email || !password) {\n            setError('E-posta ve şifre gerekli');\n            return;\n          }\n          setError(null);\n          onSubmit(email, password);\n        }}\n      />\n    </View>\n  );\n}\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/src/presentation/screens/LoginScreen.tsx"},
		},
		{
			ID:          "seed-expo-backend-handler",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: backend/internal/http/items.go\nBrif: Yerel items listesi; barındırma yok.",
			Output:      "package httpapi\n\nimport (\n\t\"encoding/json\"\n\t\"net/http\"\n)\n\ntype Item struct {\n\tID       string `json:\"id\"`\n\tTitle    string `json:\"title\"`\n\tQuantity int    `json:\"quantity\"`\n}\n\nfunc ItemsHandler(w http.ResponseWriter, r *http.Request) {\n\tif r.Method != http.MethodGet {\n\t\thttp.Error(w, \"method\", http.StatusMethodNotAllowed)\n\t\treturn\n\t}\n\t_ = json.NewEncoder(w).Encode([]Item{{\n\t\tID: \"1\", Title: \"Filtre kahve\", Quantity: 1,\n\t}})\n}\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "backend/internal/http/items.go"},
		},

		// —— Flutter source ——
		{
			ID:          "seed-flutter-entity",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: FLUTTER\nYol: frontend/lib/features/home/domain/entities/home_item.dart\nBrif: Antrenman günlüğü satırı.",
			Output:      "final class HomeItem {\n  const HomeItem({required this.id, required this.title, required this.minutes});\n  final String id;\n  final String title;\n  final int minutes;\n}\n",
			Meta:        map[string]string{"stack": "FLUTTER", "path": "frontend/lib/features/home/domain/entities/home_item.dart"},
		},
		{
			ID:          "seed-flutter-repo",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: FLUTTER\nYol: frontend/lib/features/home/data/repositories/home_repository.dart\nBrif: Yerel API’den liste.",
			Output:      "import '../domain/entities/home_item.dart';\nimport 'package:http/http.dart' as http;\nimport 'dart:convert';\n\nclass HomeRepository {\n  HomeRepository({http.Client? client}) : _client = client ?? http.Client();\n  final http.Client _client;\n  static const _base = 'http://127.0.0.1:47001';\n\n  Future<List<HomeItem>> list() async {\n    final res = await _client.get(Uri.parse('$_base/workouts'));\n    if (res.statusCode != 200) {\n      throw StateError('workouts_failed');\n    }\n    final raw = jsonDecode(res.body) as List<dynamic>;\n    return raw\n        .map((e) => HomeItem(\n              id: e['id'] as String,\n              title: e['title'] as String,\n              minutes: e['minutes'] as int,\n            ))\n        .toList();\n  }\n}\n",
			Meta:        map[string]string{"stack": "FLUTTER", "path": "frontend/lib/features/home/data/repositories/home_repository.dart"},
		},
		{
			ID:          "seed-flutter-page",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: FLUTTER\nYol: frontend/lib/features/home/presentation/pages/home_page.dart\nBrif: Liste; loading/empty/error.",
			Output:      "import 'package:flutter/material.dart';\nimport '../../domain/entities/home_item.dart';\nimport '../../data/repositories/home_repository.dart';\n\nclass HomePage extends StatefulWidget {\n  const HomePage({super.key});\n  @override\n  State<HomePage> createState() => _HomePageState();\n}\n\nclass _HomePageState extends State<HomePage> {\n  final _repo = HomeRepository();\n  late Future<List<HomeItem>> _future;\n\n  @override\n  void initState() {\n    super.initState();\n    _future = _repo.list();\n  }\n\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      appBar: AppBar(title: const Text('Antrenmanlar')),\n      body: FutureBuilder<List<HomeItem>>(\n        future: _future,\n        builder: (context, snap) {\n          if (snap.hasError) return const Center(child: Text('Yüklenemedi'));\n          if (!snap.hasData) return const Center(child: CircularProgressIndicator());\n          final items = snap.data!;\n          if (items.isEmpty) return const Center(child: Text('Kayıt yok'));\n          return ListView(\n            children: [\n              for (final item in items)\n                ListTile(title: Text(item.title), subtitle: Text('${item.minutes} dk')),\n            ],\n          );\n        },\n      ),\n    );\n  }\n}\n",
			Meta:        map[string]string{"stack": "FLUTTER", "path": "frontend/lib/features/home/presentation/pages/home_page.dart"},
		},

		// —— Native Swift ——
		{
			ID:          "seed-swift-entity",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: NATIVE\nYol: frontend/Domain/Note.swift\nBrif: Not defteri entity.",
			Output:      "import Foundation\n\nstruct Note: Identifiable, Equatable {\n  let id: String\n  var title: String\n  var body: String\n}\n",
			Meta:        map[string]string{"stack": "NATIVE", "path": "frontend/Domain/Note.swift"},
		},
		{
			ID:          "seed-swift-view",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: NATIVE\nYol: frontend/Presentation/Home/HomeView.swift\nBrif: Not listesi.",
			Output:      "import SwiftUI\n\nstruct HomeView: View {\n  let notes: [Note]\n  let errorMessage: String?\n\n  var body: some View {\n    Group {\n      if let errorMessage {\n        Text(errorMessage)\n      } else if notes.isEmpty {\n        Text(\"Not yok\")\n      } else {\n        List(notes) { note in\n          Text(note.title)\n        }\n      }\n    }\n    .navigationTitle(\"Notlar\")\n  }\n}\n",
			Meta:        map[string]string{"stack": "NATIVE", "path": "frontend/Presentation/Home/HomeView.swift"},
		},
		{
			ID:          "seed-swift-login",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: NATIVE\nYol: frontend/Presentation/Auth/LoginView.swift\nBrif: E-posta girişi; SMS yok.",
			Output:      "import SwiftUI\n\nstruct LoginView: View {\n  @State private var email = \"\"\n  @State private var password = \"\"\n  @State private var error: String?\n  var onSubmit: (String, String) -> Void\n\n  var body: some View {\n    Form {\n      TextField(\"E-posta\", text: $email)\n        .textInputAutocapitalization(.never)\n        .keyboardType(.emailAddress)\n      SecureField(\"Şifre\", text: $password)\n      if let error { Text(error).foregroundStyle(.red) }\n      Button(\"Giriş\") {\n        guard !email.isEmpty, !password.isEmpty else {\n          error = \"E-posta ve şifre gerekli\"\n          return\n        }\n        error = nil\n        onSubmit(email, password)\n      }\n    }\n    .navigationTitle(\"Giriş\")\n  }\n}\n",
			Meta:        map[string]string{"stack": "NATIVE", "path": "frontend/Presentation/Auth/LoginView.swift"},
		},

		// —— README / architecture ——
		{
			ID:          "seed-readme-expo",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Müşteri teslim README yaz. Barındırma yok; klasör/zip/git. Yığın dilini koru.",
			Input:       "Proje: Kahve sipariş\nYığın: EXPO\nBrif:\nYerel backend ile sipariş listesi.",
			Output:      "# Kahve sipariş\n\nExpo (TypeScript) + yerel backend. Cherry barındırmaz.\n\n## Çalıştırma\n\n```bash\ncd backend && go run .\ncd frontend && npx expo start\n```\n\n## Yapı\n\n- `frontend/src/domain` — entity / use case\n- `frontend/src/data` — repository\n- `frontend/src/presentation` — ekranlar\n- `maestro/` — UI akışları\n- `preview/` — stüdyo maketi; teslim zip’ine koyma\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "README.md"},
		},
		{
			ID:          "seed-arch-expo",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yığın için Clean Architecture özetini yaz. Katmanları karıştırma.",
			Input:       "Yığın: EXPO\nDosya: frontend/ARCHITECTURE.md",
			Output:      "# Architecture (Expo)\n\n- **domain**: entity + use case; framework yok.\n- **data**: repository, DTO, HTTP client.\n- **presentation**: screens / hooks; domain’i çağırır.\n- **backend/**: müşteri API’si (yerel aktif); Cherry GraphQL değil.\n- **maestro/**: cihaz yoksa SKIPPED.\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/ARCHITECTURE.md"},
		},

		// —— Maestro ——
		{
			ID:          "seed-maestro-login-skipped",
			Kind:        "maestro",
			Source:      "seed",
			Instruction: "Maestro YAML yaz. Cihaz yoksa sonuç SKIPPED olur; PASSED uydurma.",
			Input:       "Akış: login.yaml\nSonuç: SKIPPED\nNot: Emülatör yok. PASSED sayılmaz.",
			Output:      "appId: com.cherry.demo\n---\n- launchApp\n- assertVisible: \"Giriş\"\n- tapOn: \"E-posta\"\n- inputText: \"user@example.com\"\n- tapOn: \"Şifre\"\n- inputText: \"••••••••\"\n- tapOn: \"Giriş yap\"\n",
			Meta:        map[string]string{"flow": "login.yaml", "result": "SKIPPED"},
		},
		{
			ID:          "seed-maestro-home-skipped",
			Kind:        "maestro",
			Source:      "seed",
			Instruction: "Maestro YAML yaz. Cihaz yoksa sonuç SKIPPED olur; PASSED uydurma.",
			Input:       "Akış: home.yaml\nSonuç: SKIPPED\nNot: Cihaz yoksa SKIPPED.",
			Output:      "appId: com.cherry.demo\n---\n- launchApp\n- assertVisible: \"Siparişler\"\n",
			Meta:        map[string]string{"flow": "home.yaml", "result": "SKIPPED"},
		},
		{
			ID:          "seed-maestro-login-passed",
			Kind:        "maestro",
			Source:      "seed",
			Instruction: "Maestro YAML yaz. Cihaz yoksa sonuç SKIPPED olur; PASSED uydurma.",
			Input:       "Akış: login.yaml\nSonuç: PASSED\nNot: Emülatör bağlı; gerçek koşu.",
			Output:      "appId: com.cherry.demo\n---\n- launchApp\n- assertVisible: \"Giriş\"\n- tapOn:\n    id: email\n- inputText: \"demo@cherry.local\"\n- tapOn:\n    id: password\n- inputText: \"demo-pass\"\n- tapOn: \"Giriş yap\"\n- assertVisible: \"Siparişler\"\n",
			Meta:        map[string]string{"flow": "login.yaml", "result": "PASSED"},
		},
		{
			ID:          "seed-maestro-inventory",
			Kind:        "maestro",
			Source:      "seed",
			Instruction: "Maestro YAML yaz. Cihaz yoksa sonuç SKIPPED olur; PASSED uydurma.",
			Input:       "Akış: inventory.yaml\nSonuç: SKIPPED\nNot: Stok listesi ekranı.",
			Output:      "appId: com.cherry.demo\n---\n- launchApp\n- assertVisible: \"Stok\"\n- assertVisible: \"Ürün ekle\"\n",
			Meta:        map[string]string{"flow": "inventory.yaml", "result": "SKIPPED"},
		},

		// —— completions / GDPR style ——
		{
			ID:          "seed-completion-redacted",
			Kind:        "completion",
			Source:      "seed",
			Instruction: "GDPR sarmalı tamamla. PII yok. İşçi A, sürüm v1.0.",
			Input:       "Brif: [REDACTED_EMAIL] için kahve uygulaması. Kod [REDACTED_CODE]. Yığın EXPO.",
			Output:      "İşçi A v1.0 plan:\n- Ekranları yığın dosyalarına böl (domain/data/presentation).\n- Maestro: login + home; cihaz yoksa SKIPPED.\n- PII yok; e-posta/kod placeholder kaldı.\n- preview/ HTML site yazma.",
			Meta:        map[string]string{"slot": "A", "version": "v1.0"},
		},
		{
			ID:          "seed-completion-patch",
			Kind:        "completion",
			Source:      "seed",
			Instruction: "Cherry ajanı: brife ve sohbet mesajına göre dosya planı veya yama öner. PII yok.",
			Input:       "Ana ekranda boş liste metni yok. Expo. HomeScreen.tsx’e empty state ekle.",
			Output:      "Yama:\n- `frontend/src/presentation/screens/HomeScreen.tsx`\n- `items.length === 0` iken `<Text>Sipariş yok</Text>` göster.\n- Repository’ye dokunma; domain use case aynı kalsın.\nMaestro home.yaml: `assertVisible: \"Sipariş yok\"` isteğe bağlı.",
			Meta:        map[string]string{"kind": "chat"},
		},
		{
			ID:          "seed-completion-no-html",
			Kind:        "completion",
			Source:      "seed",
			Instruction: "Cherry ajanı: brife ve sohbet mesajına göre dosya planı veya yama öner. PII yok.",
			Input:       "Zip’e HTML site koyup netlify’a atalım.",
			Output:      "Hayır. Teslim seçilen yığının kaynağıdır (Expo TS / Flutter Dart / SwiftUI).\n- `preview/` stüdyo maketi; zip’e girmez.\n- Barındırma v1’de yok; Bağlantılar’dan müşteri hesabı.\n- OpenCode’a HTML site yazma talimatı verme.",
			Meta:        map[string]string{"kind": "chat"},
		},
		{
			ID:          "seed-completion-worker-b",
			Kind:        "completion",
			Source:      "seed",
			Instruction: "GDPR sarmalı tamamla. PII yok. İşçi B, sürüm v1.1.",
			Input:       "Amaç: Flutter antrenman listesine detay ekranı. PII yok.",
			Output:      "İşçi B v1.1:\n- `home_item.dart` entity’ye dokunma veya `minutes` koru.\n- `presentation/pages/detail_page.dart` ekle.\n- Maestro `workout_detail.yaml` — cihaz yoksa SKIPPED.\nPII yok.",
			Meta:        map[string]string{"slot": "B", "version": "v1.1"},
		},

		// —— more domain variety ——
		{
			ID:          "seed-expo-entity-order",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: frontend/src/domain/entities/order.ts\nBrif: Sipariş durumu enum.",
			Output:      "export type OrderStatus = 'draft' | 'placed' | 'ready';\n\nexport type Order = {\n  id: string;\n  status: OrderStatus;\n  itemIds: string[];\n};\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "frontend/src/domain/entities/order.ts"},
		},
		{
			ID:          "seed-flutter-auth-entity",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: FLUTTER\nYol: frontend/lib/features/auth/domain/entities/session.dart\nBrif: Oturum; telefon yok.",
			Output:      "final class Session {\n  const Session({required this.userId, required this.email, required this.token});\n  final String userId;\n  final String email;\n  final String token;\n}\n",
			Meta:        map[string]string{"stack": "FLUTTER", "path": "frontend/lib/features/auth/domain/entities/session.dart"},
		},
		{
			ID:          "seed-backend-main",
			Kind:        "source",
			Source:      "seed",
			Instruction: "Bu yola uygun kaynak dosyayı yaz. Seçilen dil. HTML site değil.",
			Input:       "Yığın: EXPO\nYol: backend/cmd/api/main.go\nBrif: Yerel dinleme 47001.",
			Output:      "package main\n\nimport (\n\t\"log\"\n\t\"net/http\"\n\n\thttpapi \"example.com/app/backend/internal/http\"\n)\n\nfunc main() {\n\tmux := http.NewServeMux()\n\tmux.HandleFunc(\"/items\", httpapi.ItemsHandler)\n\tlog.Println(\"local api on 127.0.0.1:47001\")\n\tlog.Fatal(http.ListenAndServe(\"127.0.0.1:47001\", mux))\n}\n",
			Meta:        map[string]string{"stack": "EXPO", "path": "backend/cmd/api/main.go"},
		},
		{
			ID:          "seed-maestro-notes",
			Kind:        "maestro",
			Source:      "seed",
			Instruction: "Maestro YAML yaz. Cihaz yoksa sonuç SKIPPED olur; PASSED uydurma.",
			Input:       "Akış: notes.yaml\nSonuç: SKIPPED\nNot: SwiftUI not listesi.",
			Output:      "appId: com.cherry.notes\n---\n- launchApp\n- assertVisible: \"Notlar\"\n- assertVisible: \"Not yok\"\n",
			Meta:        map[string]string{"flow": "notes.yaml", "result": "SKIPPED"},
		},
		{
			ID:          "seed-brief-no-sms",
			Kind:        "brief",
			Source:      "seed",
			Instruction: "Cherry stüdyosu için mobil uygulama planı yaz. Seçilen yığın ve Clean Architecture. preview/ HTML site yazma. PII uydurma.",
			Input:       "Proje: Güvenli giriş\nYığın: EXPO\nBrif:\nSMS OTP istemiyorum. E-posta + şifre + cihaz kodu + TOTP.",
			Output:      "Plan (Expo):\n- Kimlik: e-posta/şifre; SMS yok; telefon kimlik değil.\n- Yeni cihaz: 6 haneli e-posta kodu.\n- TOTP isteğe bağlı; güvenilir cihazlar + oturum iptali.\n- frontend auth feature + maestro login.yaml.\n- Cherry X-benzeri güvenlik; müşteri backend yerelde.",
			Meta:        map[string]string{"stack": "EXPO", "kind": "security"},
		},
		{
			ID:          "seed-completion-connections",
			Kind:        "completion",
			Source:      "seed",
			Instruction: "Cherry ajanı: brife ve sohbet mesajına göre dosya planı veya yama öner. PII yok.",
			Input:       "Backend’i Supabase’e taşıyalım, Cherry mi host edecek?",
			Output:      "Cherry host etmez.\n- Sidebar Bağlantılar → Supabase OAuth (müşteri hesabı).\n- Üretilen backend dosyaları diskte kalır; platform Mongo/GraphQL ile karıştırma.\n- Şimdi local target ile devam; Bağlantılar sonra.",
			Meta:        map[string]string{"kind": "chat"},
		},
	}
}
